package classifier

import (
	_ "embed"
	"strings"
	"sync"
)

// The data files are generated by cmd/brandlist from CC0-licensed Wikidata
// SPARQL exports of company/brand websites (see the file headers for
// provenance). They are a transparent, versioned positive list - evidence
// only, never a blacklist, and nothing is blocked or deleted based on them.
//
//go:embed data/legit_domains.txt
var legitDomainsData string

//go:embed data/brand_tokens.txt
var derivedBrandTokensData string

var (
	brandDataOnce      sync.Once
	legitCompanyDomain map[string]bool
	derivedBrandTokens []struct {
		token string
		own   []string
	}
)

func ensureBrandData() {
	brandDataOnce.Do(func() {
		legitCompanyDomain = make(map[string]bool, 12000)
		for _, line := range strings.Split(legitDomainsData, "\n") {
			line = strings.TrimSpace(line)
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}
			legitCompanyDomain[line] = true
		}
		for _, line := range strings.Split(derivedBrandTokensData, "\n") {
			line = strings.TrimSpace(line)
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}
			token, own, ok := strings.Cut(line, "\t")
			if !ok || token == "" || own == "" {
				continue
			}
			derivedBrandTokens = append(derivedBrandTokens, struct {
				token string
				own   []string
			}{token, strings.Split(own, ",")})
		}
	})
}

// isLegitCompanyDomain reports whether the domain (or any of its parent
// domains) appears in the Wikidata-derived list of legitimate company and
// brand websites, e.g. basf.com for mail.basf.com.
func isLegitCompanyDomain(domain string) bool {
	ensureBrandData()
	d := strings.ToLower(strings.TrimSuffix(strings.TrimSpace(domain), "."))
	for d != "" {
		if legitCompanyDomain[d] {
			return true
		}
		i := strings.Index(d, ".")
		if i < 0 {
			return false
		}
		d = d[i+1:]
	}
	return false
}
